name: CI/CD Pipeline Workflow

on:
  - push

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test push line here"
      - run: echo "Starting CI/CD workflow"
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci install
      - run: echo "Pipeline ran!"