name: CI/CD Pipeline Workflow (Cyruss)

on:
  - push

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow. Status - ${{ job.status }}"
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "Status - ${{ job.status }}"
      - name: Install dependencies
        run: npm ci
      - run: echo "Pipeline run successfully. Have a great day! Status - ${{ job.status }}"
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
