name: CI/CD Pipeline Workflow (Cyruss)

on:
  - push

permissions:
  security-events: write
  contents: read

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow. Status - ${{ job.status }}"

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - run: echo "Status - ${{ job.status }}"

      - name: Install dependencies
        run: npm ci
      
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: codeql-results.sarif

      # - name: Check for CodeQL alerts in SARIF


      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_HOOK_SECRET }}

      - run: echo "Pipeline run successfully. Have a great day! Status - ${{ job.status }}"
